services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - backend_data:/app/data
    env_file:
      - ./server/armstrong/.env
    networks:
      - armstrong-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - armstrong-network

  
volumes:
  backend_data:

networks:
  armstrong-network:
    driver: bridge