services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/db.sqlite3:/app/db.sqlite3
    depends_on:
      - db
    networks:
      - armstrong-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - armstrong-network

  db:
    image: alpine/sqlite
    volumes:
      - ./data:/data
    networks:
      - armstrong-network

networks:
  armstrong-network:
    driver: bridge