# Generated by Django 5.1.2 on 2024-10-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armstrong_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
