# Generated by Django 5.1.2 on 2024-10-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armstrong_app', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('user', 'attempted_number')},
        ),
    ]
